
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 02 16:01:19 MST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 16;
  public static final int sino = 6;
  public static final int retroceder = 12;
  public static final int llave_izq = 14;
  public static final int llave_der = 15;
  public static final int inicio = 7;
  public static final int igual = 13;
  public static final int EOF = 0;
  public static final int avanzar = 9;
  public static final int entonces = 5;
  public static final int NUMERO = 19;
  public static final int error = 1;
  public static final int variable = 3;
  public static final int IDENTIFICADOR = 17;
  public static final int fin = 8;
  public static final int detener = 10;
  public static final int girar = 11;
  public static final int si = 4;
  public static final int ESTADO = 18;
  public static final int mostrar = 2;
}

