/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import compilerTools.CodeBlock;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import compilerTools.Functions;
import compilerTools.Token;
import compilerTools.Directory;
import compilerTools.ErrorLSSL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.awt.event.WindowAdapter;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;
import java.util.Stack;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estebanramoncontrerasortega made in MacBook
 */
public class Ventana_Principal extends javax.swing.JFrame {

    NumeroLinea numerolinea;
    private String title;
    private Directory directorio;
    private ArrayList<Token> tokens;
    private ArrayList<Token> tokensError;
    private ArrayList<ErrorLSSL> errores;
    private boolean codeHasBeenCompiled = false;
    private File archivoActual = null; // para saber si se abrió o guardó un archivo
    private boolean cambiosGuardados = false; // para saber si se necesita guardar antes de compilar
    private ArrayList<Token> tablaDeSimbolos;
    private TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private int direccionActual = 0;

    public Ventana_Principal() {
        initComponents();
        inicializar();
    }

    private void inicializar() {

        setTitle("#WheelScript");
        setLocationRelativeTo(null);
        btCompilar.setEnabled(false);
        directorio = new Directory(this, jtpCode, title, ".wscript");

        addWindowListener(new WindowAdapter() {
            public void windowClosing() {
                directorio.Exit();
                System.exit(0);
            }
        });

        //Numero de linea
        numerolinea = new NumeroLinea(jtpCode);
        jScrollPane1.setRowHeaderView(numerolinea);
        jtpCode.setEditable(true);

        // Listener para actualizar números de línea
        jtpCode.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                numerolinea.repaint();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                numerolinea.repaint();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                numerolinea.repaint();
            }
        });
                
        jtpCode.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                cambiosGuardados = false;
            }

            public void removeUpdate(DocumentEvent e) {
                cambiosGuardados = false;
            }

            public void changedUpdate(DocumentEvent e) {
                cambiosGuardados = false;
            }
        });
        tokens = new ArrayList<>();
        tokensError = new ArrayList<>();
        errores = new ArrayList<>();
        tablaDeSimbolos = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Nav = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpCode = new javax.swing.JTextArea();
        Panel_Errores = new javax.swing.JScrollPane();
        jtaOutputConsole = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnTablaSimbolos = new javax.swing.JButton();
        btCompilar = new javax.swing.JButton();
        lblNombreArchivo = new javax.swing.JLabel();

        Barra_Nav.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 231));

        jPanel3.setBackground(new java.awt.Color(255, 248, 231));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtpCode.setColumns(20);
        jtpCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtpCode.setRows(5);
        jtpCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpCodeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtpCode);

        Panel_Errores.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Errores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtaOutputConsole.setColumns(20);
        jtaOutputConsole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaOutputConsole.setRows(5);
        jtaOutputConsole.setDisabledTextColor(java.awt.Color.white);
        Panel_Errores.setViewportView(jtaOutputConsole);

        jPanel1.setBackground(new java.awt.Color(255, 248, 231));

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon/nuevoarchivo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon/abrirarchivo.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnTablaSimbolos.setBackground(new java.awt.Color(255, 255, 255));
        btnTablaSimbolos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon/tablasimbolos.png"))); // NOI18N
        btnTablaSimbolos.setText("Tabla de simbolos");
        btnTablaSimbolos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTablaSimbolos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTablaSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSimbolosActionPerformed(evt);
            }
        });

        btCompilar.setBackground(new java.awt.Color(255, 255, 255));
        btCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon/compilar.png"))); // NOI18N
        btCompilar.setText("Compilar");
        btCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompilarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTablaSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCompilar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(btCompilar)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTablaSimbolos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lblNombreArchivo.setText("Archivo Nuevo");
        lblNombreArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNombreArchivo.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Panel_Errores)
                        .addGap(444, 444, 444))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(441, 441, 441))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(355, 355, 355)
                        .addComponent(lblNombreArchivo)
                        .addGap(209, 209, 209))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Errores, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        jtpCode.setText("");
        lblNombreArchivo.setText("Archivo Nuevo");
        jtaOutputConsole.setText("");
        btCompilar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (archivoActual == null) { // si es nuevo
            JFileChooser fileChooser = new JFileChooser();
            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                archivoActual = fileChooser.getSelectedFile();
                guardarArchivo();
                actualizarNombreArchivo();
                btCompilar.setEnabled(true);

            }
        } else { // si ya tiene nombre
            guardarArchivo();
            btCompilar.setEnabled(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnTablaSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSimbolosActionPerformed
        mostrarTablaDeSimbolos();
    }//GEN-LAST:event_btnTablaSimbolosActionPerformed

    private void btCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompilarActionPerformed
        try {
            boolean exito = analisisLexico(); 

            if (exito) {
                JFrame frame = new JFrame("Tabla de tokens");
                frame.setSize(500, 400);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setLocationRelativeTo(this);
                frame.setResizable(true);
                
                String[] columnas = {"Componente Léxico", "Lexema", "[Linea, Columna]"};
                DefaultTableModel model = new DefaultTableModel(columnas, 0);
                
                for(Token token: tokens){
                    String compLex = token.getLexicalComp();
                    String lexema = token.getLexeme();
                    String ubicacion = "[" + token.getLine() + "," + token.getColumn() + "]";
                    model.addRow(new Object[]{compLex, lexema, ubicacion});
                }
                JTable tabla = new JTable(model);
                JScrollPane scroll =  new JScrollPane(tabla);
                frame.add(scroll);
                frame.setVisible(true);
                
                // Analisis sintactico
                boolean exitoSintactico = analisisSintactico();
                if(exitoSintactico){
                    jtaOutputConsole.append("\n Compilacion exitosa. \n");
                } else {
                    jtaOutputConsole.append("\n se encontraron errores sintacticos. \n");
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error durante la compilación: " + e.getMessage());
        }
    }//GEN-LAST:event_btCompilarActionPerformed

    private void jtpCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpCodeKeyReleased
        int keyCode = evt.getKeyCode();
        if ((keyCode >= 65 && keyCode <= 90)
                || // A-Z
                (keyCode >= 48 && keyCode <= 57)
                || // 0-9
                (keyCode >= 97 && keyCode <= 122)
                || // a-z
                (keyCode != 27
                && // No Escape
                !(keyCode >= 37 && keyCode <= 40)
                && // No flechas
                !(keyCode >= 16 && keyCode <= 18)
                && // No Shift, Ctrl, Alt
                keyCode != 524
                && // No tecla de menú (tecla Windows derecha)
                keyCode != 20)) // No Caps Lock
        {
            if (!getTitle().contains("*")) {
                setTitle(getTitle() + "*");
            }

        }
    }//GEN-LAST:event_jtpCodeKeyReleased

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            archivoActual = fileChooser.getSelectedFile();
            try {
                String contenido = new String(Files.readAllBytes(archivoActual.toPath()));
                jtpCode.setText(contenido);
                cambiosGuardados = true;
                actualizarNombreArchivo(); // función que actualiza el nombre visible
                btCompilar.setEnabled(true);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al abrir el archivo.");
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */

    private void guardarArchivo() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoActual))) {
            writer.write(jtpCode.getText());
            cambiosGuardados = true;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar el archivo.");
        }
    }

    private boolean analisisLexico() throws IOException {
        limpiarCampos();
        direccionActual = 0;
        try {
            String codigoFuente = jtpCode.getText().trim();
            if (codigoFuente.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay codigo existente");
            }
            File codigo = new File("codigo.wscript");
            FileOutputStream salida = new FileOutputStream(codigo);
            byte[] contenido = jtpCode.getText().getBytes();
            salida.write(contenido);
            salida.close();
            BufferedReader entrada = new BufferedReader(new InputStreamReader(new FileInputStream(codigo), "UTF8"));
            WheelScriptLexer lexer = new WheelScriptLexer(entrada);
            tokens.clear();
            tokensError.clear();
            
            boolean declarandoVariable = false;
            String tipoDatoActual = null;
            

            compilerTools.Token token;
            while ((token = lexer.yylex()) != null) {
            tokens.add(token);
            if (token.getLexicalComp().startsWith("ERROR")) {
                tokensError.add(token);
            }

            if (token.getLexicalComp().equals("PALABRA_RESERVADA") && token.getLexeme().equals("variable")) {
                declarandoVariable = true;
            }   
            else if (declarandoVariable && token.getLexicalComp().equals("PALABRA_RESERVADA") && 
            (token.getLexeme().equals("entero") || token.getLexeme().equals("decimal") || token.getLexeme().equals("texto"))) {
                tipoDatoActual = token.getLexeme();
            } else if (declarandoVariable && token.getLexicalComp().equals("IDENTIFICADOR")) {
                if (!tablaSimbolos.contieneSimbolo(token.getLexeme())) {
                    int tamano = calcularTamanoTipo(tipoDatoActual);
                    tablaSimbolos.agregarSimbolos(token.getLexeme(), "Identificador",
                            tipoDatoActual != null ? tipoDatoActual : "Desconocido", "Global", direccionActual);
                    direccionActual += tamano;
                }
                declarandoVariable = false; // Finalizamos declaración
                tipoDatoActual = null;
            }
                
        }
            
            tablaDeSimbolos.addAll(tokens);

            if (!tokensError.isEmpty()) {
                StringBuilder errores = new StringBuilder();
                for (compilerTools.Token t : tokensError) {
                    String tipo = t.getLexicalComp();
                    errores.append("Error léxico en la linea ").append(t.getLine()).append(", ");
                    switch (tipo) {
                        case "ERROR_IDENTIFICADOR_ES_PALABRA_RESERVADA":
                            errores.append("Un identificador no puede ser una palabra reservada. Usa un nombre válido y distinto\n");
                            break;
                        case "ERROR_COMENTARIO":
                            errores.append("Comentario mal escrito (Usa // para los comentarios)\n");
                            break;
                        case "ERROR_IDENTIFICADOR_INVALIDO":
                        errores.append("Un identificador no puede comenzar con un número. Usa algo como 'velocidad9'\n\n");
                        break;
                        case "ERROR_CADENA_NO_CERRADA":
                            errores.append("Falta la comilla final (\"). Asegúrate de cerrar la cadena.\n\n");
                            break;
                        case "ERROR_NUMERO_MAL_FORMADO":
                            errores.append("El número contiene múltiples puntos decimales. Usa solo uno (ejemplo: 5.4).\n\n");
                            break;
                        case "ERROR_CARACTER_INVALIDO":
                            errores.append("Usa solo caracteres permitidos en el lenguaje (letras, números, símbolos válidos).\n\n");
                            break;
                        case "ERROR":
                        default:
                            errores.append("Revisa la cadena.\n\n");
                        break;
                    }
                }
                
                   // 
                jtaOutputConsole.setForeground(Color.RED);
                jtaOutputConsole.setText("");
                jtaOutputConsole.setText(errores.toString());
                return false;
            }

            jtaOutputConsole.setForeground(Color.BLUE);
            jtaOutputConsole.setText("COMPILACION EXITOSA. SIN ERRORES LÉXICOS.");
            return true;

        } catch (Exception ex) {
            jtaOutputConsole.setForeground(Color.RED);
            jtaOutputConsole.setText("Error: " + ex.getMessage());
        }
        return false;
    }
    
    private boolean analisisSintactico() {
        jtaOutputConsole.setForeground(Color.BLUE);
        jtaOutputConsole.setText("Iniciando análisis sintáctico LL(1)...\n");

        Map<String, Map<String, String[]>> tablaLL1 = new HashMap<>();

        // Gramática completa adaptada a tu lexer y gramática
        addEntry(tablaLL1, "programa", "INICIO_PROGRAMA", new String[]{"INICIO_PROGRAMA", "LLAVE_ABRE", "instrucciones", "LLAVE_CIERRA", "FIN_BLOQUE"});

        addEntry(tablaLL1, "instrucciones", "DECLARACION_VAR", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "IDENTIFICADOR", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "ENTRADA_SALIDA", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "COMANDO_ACCION", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "CONDICIONAL", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "CICLO", new String[]{"instruccion", "instrucciones"});
        addEntry(tablaLL1, "instrucciones", "LLAVE_CIERRA", new String[]{}); // ε

        addEntry(tablaLL1, "instruccion", "DECLARACION_VAR", new String[]{"declaracion_variable"});
        addEntry(tablaLL1, "instruccion", "IDENTIFICADOR", new String[]{"asignacion"});
        addEntry(tablaLL1, "instruccion", "ENTRADA_SALIDA", new String[]{"mostrar_instr"});
        addEntry(tablaLL1, "instruccion", "COMANDO_ACCION", new String[]{"accion"});
        addEntry(tablaLL1, "instruccion", "CONDICIONAL", new String[]{"condicional"});
        addEntry(tablaLL1, "instruccion", "CICLO", new String[]{"ciclo"});

        addEntry(tablaLL1, "declaracion_variable", "DECLARACION_VAR", new String[]{"DECLARACION_VAR", "TIPO_DATO", "IDENTIFICADOR", "PUNTO_COMA"});
        addEntry(tablaLL1, "asignacion", "IDENTIFICADOR", new String[]{"IDENTIFICADOR", "OP_ASIGNACION", "expresion", "PUNTO_COMA"});
        addEntry(tablaLL1, "mostrar_instr", "ENTRADA_SALIDA", new String[]{"ENTRADA_SALIDA", "PUNTO_COMA"});
        addEntry(tablaLL1, "accion", "COMANDO_ACCION", new String[]{"COMANDO_ACCION", "PUNTO_COMA"});

        addEntry(tablaLL1, "condicional", "CONDICIONAL", new String[]{"CONDICIONAL", "SENSOR", "OP_COMPARACION", "ESTADO_SENSOR", "CONDICIONAL", "LLAVE_ABRE", "instrucciones", "LLAVE_CIERRA", "sino_opcional"});
        addEntry(tablaLL1, "sino_opcional", "CONDICIONAL", new String[]{"CONDICIONAL", "LLAVE_ABRE", "instrucciones", "LLAVE_CIERRA"});
        addEntry(tablaLL1, "sino_opcional", "LLAVE_CIERRA", new String[]{}); // ε

        addEntry(tablaLL1, "ciclo", "CICLO", new String[]{"CICLO", "NUMERO", "LLAVE_ABRE", "instrucciones", "LLAVE_CIERRA"});
        addEntry(tablaLL1, "expresion", "NUMERO", new String[]{"NUMERO"});
        addEntry(tablaLL1, "expresion", "IDENTIFICADOR", new String[]{"IDENTIFICADOR"});
        addEntry(tablaLL1, "expresion", "CADENA", new String[]{"CADENA"});
        addEntry(tablaLL1, "expresion", "SENSOR", new String[]{"SENSOR"});

            // Obtener tokens reales
            List<String> tokensEntrada = new ArrayList<>();
            try {
                String codigoFuente = jtpCode.getText().trim();
                if (codigoFuente.isEmpty()) {
                    jtaOutputConsole.append("❌ No hay código para analizar.\n");
                    return false;
                }
                File tempFile = new File("codigoTemp.wscript");
                try (FileOutputStream fos = new FileOutputStream(tempFile)) {
                    fos.write(codigoFuente.getBytes());
                }

                WheelScriptLexer lexer = new WheelScriptLexer(new BufferedReader(new InputStreamReader(new FileInputStream(tempFile), "UTF-8")));
                compilerTools.Token token;
                while ((token = lexer.yylex()) != null) {
                    tokensEntrada.add(token.getLexicalComp());
                }
                tokensEntrada.add("$");
            } catch (Exception e) {
                jtaOutputConsole.append("❌ Error al obtener tokens del lexer: " + e.getMessage() + "\n");
                return false;
            }

            Stack<String> pila = new Stack<>();
            pila.push("$");
            pila.push("programa");

            int index = 0;
            while (!pila.isEmpty()) {
                String tope = pila.peek();
                String simbolo = tokensEntrada.get(index);

                jtaOutputConsole.append("🪜 Pila: " + pila + "\n");
                jtaOutputConsole.append("🔎 Token actual: " + simbolo + "\n");

                if (tope.equals(simbolo)) {
                    pila.pop();
                    index++;
                    jtaOutputConsole.append("Emparejado: " + simbolo + "\n");
                } else if (isTerminalLL1(tope)) {
                    jtaOutputConsole.append("❌ Error: Se esperaba " + tope + " pero se encontró " + simbolo + "\n");
                    return false;
                } else {
                    Map<String, String[]> fila = tablaLL1.get(tope);
                    if (fila != null && fila.containsKey(simbolo)) {
                        pila.pop();
                        String[] produccion = fila.get(simbolo);
                        if (produccion.length == 0) {
                            jtaOutputConsole.append(tope + " -> ε\n");
                        } else {
                            jtaOutputConsole.append(tope + " -> " + String.join(" ", produccion) + "\n");
                            // Aseguramos que si el siguiente token es un terminal (como LLAVE_ABRE), se procese correctamente
                            for (int i = produccion.length - 1; i >= 0; i--) {
                                pila.push(produccion[i]);
                            }
                        }
                    } else {
                        jtaOutputConsole.append("❌ Error: No hay producción para (" + tope + ", " + simbolo + ")\n");
                        return false;
                    }
                }
            }

            if (index == tokensEntrada.size()) {
                jtaOutputConsole.append("✔ Análisis sintáctico LL(1) exitoso.\n");
                return true;
            } else {
                jtaOutputConsole.append("❌ Error: Tokens restantes sin analizar.\n");
                return false;
            }
        }

    private void addEntry(Map<String, Map<String, String[]>> tabla, String noTerminal, String terminal, String[] produccion) {
        tabla.putIfAbsent(noTerminal, new HashMap<>());
        tabla.get(noTerminal).put(terminal, produccion);
    }

    private boolean isTerminalLL1(String simbolo) {
        return simbolo.matches("INICIO_PROGRAMA|LLAVE_ABRE|LLAVE_CIERRA|FIN_BLOQUE|DECLARACION_VAR|TIPO_DATO|IDENTIFICADOR|NUMERO|CADENA|OP_ASIGNACION|ENTRADA_SALIDA|COMANDO_ACCION|CONDICIONAL|SINO|SENSOR|ESTADO_SENSOR|OP_COMPARACION|PUNTO_COMA|\\$");
    }

    
    // Método para calcular el tamaño de cada tipo de dato
    private int calcularTamanoTipo(String tipo) {
        if (tipo == null) return 4;
        switch (tipo.toLowerCase()) {
            case "entero":
                return 4;
            case "decimal":
                return 8;
            case "texto":
                return 16;
            default:
                return 4;
        }
    }
    
    
    private void mostrarTablaDeSimbolos(){
        if (tablaSimbolos.getSimbolos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay símbolos cargados.");
            return;
        }
        String[] columnas = {"Nombre", "Tipo", "TipoDato", "Ámbito", "Dirección"};
        String [][] datos = new String[tablaSimbolos.getSimbolos().size()][5];
        int i = 0;
        for (TablaSimbolos.Simbolo s: tablaSimbolos.getSimbolos().values()) {
            datos[i++] = s.toArray();
        }
        JTable tabla = new JTable(new DefaultTableModel(datos, columnas));
        JScrollPane scroll = new JScrollPane(tabla);
        JFrame frame = new JFrame("Tabla de Símbolos");
        frame.setSize(500, 300);
        frame.add(scroll);
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }

    private void limpiarCampos() {
        jtaOutputConsole.setText("");
        tokens.clear();
    }

    private void actualizarNombreArchivo() {
        if (archivoActual != null) {
            lblNombreArchivo.setText("Archivo: " + archivoActual.getName());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    public void clearAllComp() {
        jtaOutputConsole.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Barra_Nav;
    private javax.swing.JScrollPane Panel_Errores;
    private javax.swing.JButton btCompilar;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTablaSimbolos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaOutputConsole;
    private javax.swing.JTextArea jtpCode;
    private javax.swing.JLabel lblNombreArchivo;
    // End of variables declaration//GEN-END:variables
}