/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author estebanramoncontrerasortega
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Nav = new javax.swing.JMenuItem();
        Panel_Errores = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        Nav_Bar = new javax.swing.JMenuBar();
        Archivo_Option = new javax.swing.JMenu();
        Archivo_New_Option = new javax.swing.JMenuItem();
        Archivo_Abrir_Nuevo_Option = new javax.swing.JMenuItem();
        Guardar_Option = new javax.swing.JMenu();
        Compilar_Option = new javax.swing.JMenu();
        Tablas_Option = new javax.swing.JMenu();
        Tabla_Fija_Option = new javax.swing.JMenuItem();
        Tabla_De_Simbolos_Option = new javax.swing.JMenuItem();
        Tabla_Lexico_Option = new javax.swing.JMenuItem();

        Barra_Nav.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Errores.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Archivo_Option.setText("Archivo");

        Archivo_New_Option.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Archivo_New_Option.setText("Nuevo");
        Archivo_New_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Archivo_New_OptionActionPerformed(evt);
            }
        });
        Archivo_Option.add(Archivo_New_Option);

        Archivo_Abrir_Nuevo_Option.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Archivo_Abrir_Nuevo_Option.setText("Abrir Archivo");
        Archivo_Abrir_Nuevo_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Archivo_Abrir_Nuevo_OptionActionPerformed(evt);
            }
        });
        Archivo_Option.add(Archivo_Abrir_Nuevo_Option);

        Nav_Bar.add(Archivo_Option);

        Guardar_Option.setText("Guardar");
        Nav_Bar.add(Guardar_Option);

        Compilar_Option.setText("Compilar");
        Nav_Bar.add(Compilar_Option);

        Tablas_Option.setText("Tablas Simbolos");

        Tabla_Fija_Option.setText("Tabla Fija");
        Tablas_Option.add(Tabla_Fija_Option);

        Tabla_De_Simbolos_Option.setText("Tabla De Simbólos");
        Tablas_Option.add(Tabla_De_Simbolos_Option);

        Tabla_Lexico_Option.setText("Tabla Léxico");
        Tablas_Option.add(Tabla_Lexico_Option);

        Nav_Bar.add(Tablas_Option);

        setJMenuBar(Nav_Bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Panel_Errores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Errores, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Archivo_Abrir_Nuevo_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Archivo_Abrir_Nuevo_OptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Archivo_Abrir_Nuevo_OptionActionPerformed

    private void Archivo_New_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Archivo_New_OptionActionPerformed
        // TODO add your handling code here:
        System.out.println("hola");
    }//GEN-LAST:event_Archivo_New_OptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Archivo_Abrir_Nuevo_Option;
    private javax.swing.JMenuItem Archivo_New_Option;
    private javax.swing.JMenu Archivo_Option;
    private javax.swing.JMenuItem Barra_Nav;
    private javax.swing.JMenu Compilar_Option;
    private javax.swing.JMenu Guardar_Option;
    private javax.swing.JMenuBar Nav_Bar;
    private javax.swing.JScrollPane Panel_Errores;
    private javax.swing.JMenuItem Tabla_De_Simbolos_Option;
    private javax.swing.JMenuItem Tabla_Fija_Option;
    private javax.swing.JMenuItem Tabla_Lexico_Option;
    private javax.swing.JMenu Tablas_Option;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
