/* The following code was generated by JFlex 1.4.3 on 19/05/25, 00:36 */

package codigo;
import compilerTools.Token;
import codigo.TablaSimbolos;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 19/05/25, 00:36 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/10mo Semestre/Lenguajes y Automatas/Proyecto/compilador/src/codigo/WheelScriptLexer.flex</tt>
 */
public class WheelScriptLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\53\1\50\2\0\1\53\22\0\1\53\1\31\1\45\5\0"+
    "\1\41\1\42\2\55\1\43\1\55\1\54\1\51\12\46\1\0\1\44"+
    "\1\33\1\30\1\32\2\0\32\52\1\37\1\47\1\40\1\0\1\24"+
    "\1\0\1\1\1\17\1\16\1\10\1\11\1\22\1\6\1\26\1\7"+
    "\2\52\1\21\1\20\1\3\1\15\1\14\1\25\1\5\1\13\1\12"+
    "\1\23\1\2\1\52\1\27\1\34\1\4\1\35\1\0\1\36\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\13\2\1\3\5\2\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\2\23\4\2\1\24"+
    "\10\2\1\25\10\2\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\2\0\1\35\27\2\1\36\1\2\2\0"+
    "\20\2\1\25\6\2\1\37\1\2\1\21\1\0\6\2"+
    "\1\40\6\2\1\41\7\2\1\42\5\2\1\43\1\2"+
    "\1\44\12\2\1\45\5\2\1\46\1\47\1\50\1\51"+
    "\7\2\1\52\15\2\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\346\0\u0256\0\u0284"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6\0\346"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\56\0\56"+
    "\0\u03f4\0\u0422\0\u0450\0\u047e\0\56\0\u04ac\0\u04da\0\u0508"+
    "\0\u0536\0\346\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u061c\0\u064a"+
    "\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba"+
    "\0\u07e8\0\u0816\0\u0844\0\56\0\56\0\56\0\56\0\u03f4"+
    "\0\56\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986"+
    "\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6"+
    "\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66"+
    "\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\346\0\u0d4c\0\u0d7a\0\u0da8"+
    "\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18"+
    "\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088"+
    "\0\346\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e\0\u119c\0\346"+
    "\0\u11ca\0\u0d7a\0\u11f8\0\u1226\0\u1254\0\u1282\0\u12b0\0\u12de"+
    "\0\u130c\0\346\0\u133a\0\u1368\0\u1396\0\u13c4\0\u13f2\0\u1420"+
    "\0\346\0\u144e\0\u147c\0\u14aa\0\u14d8\0\u1506\0\u1534\0\u1562"+
    "\0\u11f8\0\u1590\0\u15be\0\u15ec\0\u161a\0\u1648\0\346\0\u1676"+
    "\0\346\0\u16a4\0\u16d2\0\u1700\0\u172e\0\u175c\0\u178a\0\u17b8"+
    "\0\u17e6\0\u1814\0\u1842\0\346\0\u1870\0\u189e\0\u18cc\0\u18fa"+
    "\0\u1928\0\346\0\346\0\346\0\346\0\u1956\0\u1984\0\u19b2"+
    "\0\u19e0\0\u1a0e\0\u1a3c\0\u1a6a\0\346\0\u1a98\0\u1ac6\0\u1af4"+
    "\0\u1b22\0\u1b50\0\u1b7e\0\u1bac\0\u1bda\0\u1c08\0\u1c36\0\u1c64"+
    "\0\u1c92\0\u1cc0\0\346";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\6\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\5\6\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\2\1\43\1\44\1\6\1\43"+
    "\2\45\57\0\1\6\1\46\11\6\1\47\1\6\1\50"+
    "\11\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\1\51\26\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\14\6\1\52\12\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\27\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\10\6\1\53\3\6\1\54\12\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\6\6"+
    "\1\55\20\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\2\6\1\56\24\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\10\6\1\57\16\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\2\6\1\60\7\6"+
    "\1\61\14\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\10\6\1\62\16\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\6\6\1\63\1\6\1\64\16\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\14\6"+
    "\1\65\12\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\14\6\1\66\12\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\6\6\1\67\5\6\1\70\12\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\10\6"+
    "\1\71\16\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\6\6\1\72\13\6\1\73\4\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\33\0\1\74\55\0\1\75"+
    "\55\0\1\76\55\0\1\77\25\0\45\100\1\101\2\100"+
    "\1\0\5\100\1\0\27\102\4\0\1\102\11\0\1\42"+
    "\1\103\2\0\1\102\1\0\1\104\51\0\1\43\2\0"+
    "\1\43\53\0\1\105\5\0\1\106\26\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\1\107\26\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\11\6\1\110"+
    "\15\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\4\6\1\111\22\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\11\6\1\112\1\6\1\113\13\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\17\6\1\114"+
    "\7\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\4\6\1\115\22\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\1\116\5\6\1\117\20\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\11\6\1\120\3\6"+
    "\1\121\11\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\11\6\1\122\3\6\1\123\11\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\13\6\1\124\13\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\26\6"+
    "\1\125\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\2\6\1\126\24\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\2\6\1\127\24\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\2\6\1\130\24\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\15\6\1\131"+
    "\11\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\10\6\1\132\16\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\12\6\1\133\14\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\10\6\1\134\16\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\2\6\1\135"+
    "\24\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\2\6\1\136\24\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\27\102\4\0\1\102\11\0\1\102\3\0"+
    "\1\102\3\0\50\137\1\0\5\137\46\0\1\140\7\0"+
    "\50\105\1\0\5\105\1\0\2\6\1\141\24\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\5\6\1\115"+
    "\21\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\6\6\1\142\20\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\6\6\1\143\20\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\4\6\1\144\7\6\1\145"+
    "\12\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\10\6\1\146\16\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\13\6\1\147\13\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\1\150\26\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\15\6\1\151\11\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\15\6"+
    "\1\152\11\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\10\6\1\153\16\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\6\6\1\154\20\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\10\6\1\155\3\6"+
    "\1\156\12\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\10\6\1\157\16\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\10\6\1\55\16\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\11\6\1\160\15\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\14\6"+
    "\1\161\12\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\12\6\1\162\14\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\11\6\1\163\1\164\14\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\6\6\1\165"+
    "\20\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\2\6\1\166\24\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\11\6\1\167\15\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\4\6\1\170\22\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\15\6\1\171"+
    "\11\6\4\0\1\6\11\0\1\6\3\0\1\6\51\0"+
    "\1\172\55\0\1\140\5\0\1\173\2\0\3\6\1\115"+
    "\23\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\1\6\1\174\25\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\1\175\26\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\14\6\1\176\12\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\4\6\1\177\22\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\11\6"+
    "\1\200\15\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\10\6\1\201\16\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\4\6\1\202\22\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\11\6\1\203\15\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\6\6"+
    "\1\204\20\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\2\6\1\205\24\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\17\6\1\206\7\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\4\6\1\160\22\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\2\6"+
    "\1\207\24\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\2\6\1\210\24\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\14\6\1\211\12\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\14\6\1\212\12\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\6\6"+
    "\1\213\20\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\11\6\1\214\15\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\2\6\1\215\24\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\11\6\1\216\15\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\4\6"+
    "\1\217\22\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\6\6\1\220\20\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\51\0\1\221\10\0\1\222\26\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\16\6\1\223"+
    "\10\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\15\6\1\224\11\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\2\6\1\225\24\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\6\6\1\226\20\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\4\6\1\227"+
    "\22\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\6\6\1\230\20\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\14\6\1\231\12\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\10\6\1\150\16\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\1\232\26\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\15\6"+
    "\1\233\11\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\7\6\1\205\17\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\4\6\1\234\22\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\2\6\1\235\24\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\1\236"+
    "\26\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\1\202\26\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\4\6\1\237\22\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\1\134\26\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\14\6\1\240\12\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\7\6\1\241"+
    "\17\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\20\6\1\242\6\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\10\6\1\210\16\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\1\243\26\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\4\6\1\244\22\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\1\6"+
    "\1\241\25\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\20\6\1\211\6\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\10\6\1\245\16\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\23\6\1\246\3\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\22\6"+
    "\1\247\4\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\2\6\1\250\24\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\1\251\26\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\2\6\1\252\24\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\14\6\1\253"+
    "\12\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\10\6\1\254\16\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\4\6\1\255\22\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\12\6\1\161\14\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\6\6\1\256"+
    "\1\257\11\6\1\260\5\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\1\201\26\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\11\6\1\261\15\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\12\6\1\244"+
    "\14\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\3\6\1\262\23\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\10\6\1\263\16\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\4\6\1\264\22\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\10\6\1\265"+
    "\16\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\24\6\1\266\2\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\4\6\1\267\22\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\14\6\1\270\12\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\22\6\1\271"+
    "\4\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\10\6\1\272\16\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\2\6\1\273\24\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\6\6\1\274\20\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\15\6\1\275"+
    "\11\6\4\0\1\6\11\0\1\6\3\0\1\6\4\0"+
    "\11\6\1\276\15\6\4\0\1\6\11\0\1\6\3\0"+
    "\1\6\4\0\10\6\1\277\16\6\4\0\1\6\11\0"+
    "\1\6\3\0\1\6\4\0\25\6\1\300\1\6\4\0"+
    "\1\6\11\0\1\6\3\0\1\6\4\0\1\301\26\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\4\0\4\6"+
    "\1\302\22\6\4\0\1\6\11\0\1\6\3\0\1\6"+
    "\4\0\14\6\1\303\12\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\4\0\20\6\1\303\6\6\4\0\1\6"+
    "\11\0\1\6\3\0\1\6\4\0\7\6\1\300\17\6"+
    "\4\0\1\6\11\0\1\6\3\0\1\6\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7406];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\26\1\10\11\4\1\1\11\26\1\4\11"+
    "\1\1\1\11\1\1\2\0\32\1\2\0\32\1\1\0"+
    "\110\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[195];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();

    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public WheelScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public WheelScriptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 41: 
          { return token(yytext(), "RETORNO", yyline, yycolumn);
          }
        case 44: break;
        case 14: 
          { return token(yytext(), "COMA", yyline, yycolumn);
          }
        case 45: break;
        case 15: 
          { return token(yytext(), "PUNTO_COMA", yyline, yycolumn);
          }
        case 46: break;
        case 4: 
          { return token(yytext(), "OP_ASIGNACION", yyline, yycolumn);
          }
        case 47: break;
        case 27: 
          { return token(yytext(), "CADENA", yyline, yycolumn);
          }
        case 48: break;
        case 22: 
          { return token(yytext(), "OP_COMPARACION", yyline, yycolumn);
          }
        case 49: break;
        case 2: 
          { if (tablaSimbolos.esReservada(yytext())) {
        return token(yytext(), "PALABRA_RESERVADA", yyline, yycolumn);
    } else {
        return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
    }
          }
        case 50: break;
        case 23: 
          { return token(yytext(), "OP_DIFERENTE", yyline, yycolumn);
          }
        case 51: break;
        case 28: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 52: break;
        case 13: 
          { return token(yytext(), "PAREN_CIERRA", yyline, yycolumn);
          }
        case 53: break;
        case 37: 
          { return token(yytext(), "CICLO", yyline, yycolumn);
          }
        case 54: break;
        case 3: 
          { return token(yytext(), "OP_LOGICO_OR", yyline, yycolumn);
          }
        case 55: break;
        case 7: 
          { return token(yytext(), "OP_LOGICO_AND", yyline, yycolumn);
          }
        case 56: break;
        case 16: 
          { return token(yytext(), "COMILLA_DOBLE", yyline, yycolumn);
          }
        case 57: break;
        case 30: 
          { return token(yytext(), "FIN_BLOQUE", yyline, yycolumn);
          }
        case 58: break;
        case 25: 
          { return token(yytext(), "OP_MENOR_IGUAL", yyline, yycolumn);
          }
        case 59: break;
        case 43: 
          { return token(yytext(), "SENSOR", yyline, yycolumn);
          }
        case 60: break;
        case 33: 
          { return token(yytext(), "TIPO_DATO", yyline, yycolumn);
          }
        case 61: break;
        case 9: 
          { return token(yytext(), "LLAVE_CIERRA", yyline, yycolumn);
          }
        case 62: break;
        case 34: 
          { return token(yytext(), "ERROR_NUMERO_MAL_FORMADO", yyline, yycolumn);
          }
        case 63: break;
        case 32: 
          { return token(yytext(), "COMANDO_ACCION", yyline, yycolumn);
          }
        case 64: break;
        case 39: 
          { return token(yytext(), "ESTADO_SENSOR", yyline, yycolumn);
          }
        case 65: break;
        case 20: 
          { return token(yytext(), "OP_LOGICO_NOT", yyline, yycolumn);
          }
        case 66: break;
        case 21: 
          { return token(yytext(), "CONDICIONAL", yyline, yycolumn);
          }
        case 67: break;
        case 5: 
          { return token(yytext(), "OP_MAYOR", yyline, yycolumn);
          }
        case 68: break;
        case 38: 
          { return token(yytext(), "FUNCION_DEF", yyline, yycolumn);
          }
        case 69: break;
        case 40: 
          { return token(yytext(), "DECLARACION_VAR", yyline, yycolumn);
          }
        case 70: break;
        case 12: 
          { return token(yytext(), "PAREN_ABRE", yyline, yycolumn);
          }
        case 71: break;
        case 42: 
          { return token(yytext(), "DECLARACION_CONST", yyline, yycolumn);
          }
        case 72: break;
        case 36: 
          { return token(yytext(), "INICIO_PROGRAMA", yyline, yycolumn);
          }
        case 73: break;
        case 24: 
          { return token(yytext(), "OP_MAYOR_IGUAL", yyline, yycolumn);
          }
        case 74: break;
        case 26: 
          { return token(yytext(), "ERROR_CADENA_NO_CERRADA", yyline, yycolumn);
          }
        case 75: break;
        case 31: 
          { return token(yytext(), "ENTRADA_SALIDA", yyline, yycolumn);
          }
        case 76: break;
        case 6: 
          { return token(yytext(), "OP_MENOR", yyline, yycolumn);
          }
        case 77: break;
        case 1: 
          { return token(yytext(), "ERROR_CARACTER_INVALIDO", yyline, yycolumn);
          }
        case 78: break;
        case 19: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 79: break;
        case 11: 
          { return token(yytext(), "CORCHETE_CIERRA", yyline, yycolumn);
          }
        case 80: break;
        case 10: 
          { return token(yytext(), "CORCHETE_ABRE", yyline, yycolumn);
          }
        case 81: break;
        case 35: 
          { return token(yytext(), "INTERRUPTOR", yyline, yycolumn);
          }
        case 82: break;
        case 17: 
          { return token(yytext(), "NUMERO", yyline, yycolumn);
          }
        case 83: break;
        case 29: 
          { return token(yytext(), "COMENTARIO", yyline, yycolumn);
          }
        case 84: break;
        case 8: 
          { return token(yytext(), "LLAVE_ABRE", yyline, yycolumn);
          }
        case 85: break;
        case 18: 
          { /* ignorar espacios */
          }
        case 86: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
